export default {
  expo: {
    name: "DTM - DopeTz.com",
    slug: "dopetzcom",
    version: "2.4.8",
    orientation: "portrait",
    icon: "./assets/images/logos/logo-icon.png",
    userInterfaceStyle: "light",
    splash: {
      image: "./assets/images/logos/logo-main.png",
      resizeMode: "contain",
      backgroundColor: "#ffffff",
    },
    platforms: ["ios", "android", "web"],
    ios: {
      bundleIdentifier: "com.dopetzcom.dtm",
      buildNumber: "44",
      supportsTablet: true,
      requireFullScreen: false,
      infoPlist: {
        NSPhotoLibraryUsageDescription: "This app needs access to your photo library to upload product images.",
        NSCameraUsageDescription: "This app needs access to your camera to take photos for products.",
        NSLocationWhenInUseUsageDescription: "This app needs access to your location for delivery services.",
      },
    },
    android: {
      package: "com.dopetzcom.dtm",
      versionCode: 1,
      adaptiveIcon: {
        foregroundImage: "./assets/images/logos/logo-icon.png",
        backgroundColor: "#ffffff",
      },
      permissions: [
        "android.permission.CAMERA",
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE",
        "android.permission.ACCESS_FINE_LOCATION",
        "android.permission.ACCESS_COARSE_LOCATION",
        "android.permission.INTERNET",
        "android.permission.ACCESS_NETWORK_STATE",
      ],
    },
    web: {
      bundler: "metro",
      output: "static",
      favicon: "./assets/images/logos/logo-icon.png",
      name: "DTM - DopeTz.com",
      shortName: "DTM",
      description: "DTM E-commerce Platform - Your trusted online shopping destination",
      startUrl: "/",
      scope: "/",
      themeColor: "#f59207",
      backgroundColor: "#ffffff",
      display: "standalone",
      orientation: "portrait",
      appleWebApp: {
        capable: true,
        statusBarStyle: "default",
        title: "DTM",
      },
      meta: {
        title: "DTM - DopeTz.com | Your Trusted Online Shopping Destination",
        description: "Shop the latest products from DTM. Fast delivery, secure payments, and excellent customer service.",
        keywords: "DTM, ecommerce, online shopping, products, delivery",
        viewport: "width=device-width, initial-scale=1, maximum-scale=5, user-scalable=yes, shrink-to-fit=no, viewport-fit=cover",
        "theme-color": "#f59207",
        "apple-mobile-web-app-capable": "yes",
        "apple-mobile-web-app-status-bar-style": "default",
        "apple-mobile-web-app-title": "DTM",
        "format-detection": "telephone=no",
        "mobile-web-app-capable": "yes",
        "msapplication-TileColor": "#f59207",
        "msapplication-navbutton-color": "#f59207",
        "msapplication-starturl": "/",
      },
    },
    plugins: [
      "expo-asset",
      "expo-audio",
      "expo-font",
      "expo-mail-composer",
      "expo-router",
      "expo-secure-store",
      "expo-sqlite",
      "expo-video",
      "expo-web-browser"
    ],
    experiments: {
      typedRoutes: true,
    },
    extra: {
      router: {},
    },
  },
};
